name: CI cargo
on:
  workflow_call:
    inputs:
      toolchain:
        type: string
        default: "stable"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check --all-targets
      - name: Test
        run: cargo test --all-targets
